# Generated by Django 3.2.3 on 2021-05-21 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[(0, 'Success'), (1, 'Failure')], default='Success', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 16, 31, 22, 537332)),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='test_20210521', max_length=30),
        ),
    ]
