# Generated by Django 3.2.3 on 2021-05-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcapp', '0002_auto_20210521_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='time',
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
